apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: easypay-web
spec:
  maxReplicas: 10
  minReplicas: 3
  targetCPUUtilizationPercentage: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
